---
- name: Download / Install Latest odo binary
  get_url:
    url:  https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64
    dest: /usr/local/bin/odo
    mode: '0555'
    owner: root
    group: root

- name: 'Ensure bash-completion Package is Installed via ({{ ansible_pkg_mgr }})'
  include_tasks: 'pkg-install-{{ ansible_pkg_mgr }}.yaml'
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf')

- fail:
    msg: WARNING This role is not setup to deal with package manager {{ ansible_pkg_mgr }} can not verify bash-completion Package is installed, bash completions may not work
  ignore_errors: yes
  when: ansible_pkg_mgr not in ('apt', 'yum', 'dnf')

- name: Ensure obo bash_completion script exists
  ansible.builtin.copy:
    src: files/odo_completion
    dest: /etc/bash_completion.d/odo_completion
    owner: root
    group: root
    mode: '0644'

- debug:
    msg: If odo is new/updated the bash completion may not work properly until you log into a new bash shell.

